### ISSUE TITLE
Image optimisation

### ISSUE THREAD

**Issue by DaniruKun** [GoldElysium/hef-website#262]
The static images are served in their full size, Kronii's profile picture alone is **7 MB**

![image](https://user-images.githubusercontent.com/5202322/169910774-801cf8ce-a8ac-4402-9b9e-7cc8253bac92.png)

This is the first low-hanging fruit imho to reducing the load times. Kind of related to #248

**Comment by DaniruKun** [comment]
Optimised version: https://imgur.com/a/VtVwgvO
Original size: **7MB+**
New size: **627 KB**
Savings: ~11x smaller

**Comment by DaniruKun** [comment]
Honestly both, but optimizing the images to web sizes would be the first and easiest step imho.

**Comment by GoldElysium** [comment]
Linking #265, Payload is configured to auto resize images so they should be much smaller. Next/image is also an option to add on top, depending on Vercel limits
