### ISSUE TITLE
Project editor not allowing selection of server

### ISSUE THREAD

**Issue by Ninjastahr** [GoldElysium/hef-website#282]
![image](https://user-images.githubusercontent.com/10507354/182212445-cf9cd8d2-4d1c-4647-ad79-290496cb0c64.png)

**Comment by GoldElysium** [comment]
![image](https://user-images.githubusercontent.com/48455312/183678549-2d921121-b3d0-4dff-a54b-2a9f2a7a90d0.png)
Works fine here. Adding the invalid label for that, and adding wont fix, since the dashboard should be replaced by the end of the week.
