### ISSUE TITLE
question regarding submission wrapper routing

### ISSUE THREAD

**Issue by j1george** [GoldElysium/hef-website#409]
> shouldn't this just be 
> 
> ```tsx
> 
> 	if (project.flags.includes('jigsaw-puzzle')) {
> 
> ```
> 
> 
> 
> bc `project.flags.includes('kronii-puzzle')` is handled on line 98 

 _Originally posted by @j1george in [93e421c](https://github.com/GoldElysium/hef-website/commit/93e421c14c306cf266753debb68456286c528055#r150351968)_

**Comment by GoldElysium** [comment]
Still need to update that yes, `kronii-puzzle` will be removed in favor of the general `jigsaw-puzzle` flag. L98 should have been deleted, but I apparently forgot.
