### ISSUE TITLE
Better submissions UX

### ISSUE THREAD

**Issue by Ninjastahr** [GoldElysium/hef-website#79]
Currently, one has to scroll through the entire list of text submissions before seeing image submissions, which makes it unclear that there even are image submissions - a possible fix would be some kind of selection between text and image/video submissions.

Original title: Scrolling through all of the text submissions to reach the image submissions is less than ideal UX

**Comment by GoldElysium** [comment]
Solving this by creating a filter dropdown, and creating a bar at the top with a random selection of submissions.
